-d C:\Users\Cherry\Documents\fpga_project\impl\gwsynthesis\fpga_project.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\Cherry\Documents\fpga_project\src\fpga_project.cst
-cfg C:\Users\Cherry\Documents\fpga_project\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 10
